version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      # Note: The group order matters, since updates are assigned to the first matching group.
      libcnb:
        patterns:
          - "libcnb*"
          - "libherokubuildpack"
      rust-dependencies:
        update-types:
          - "minor"
          - "patch"
