[package]
name = "languages-github-actions"
description = "GitHub Actions for the Languages Team"
version = "0.0.1"
repository = "https://github.com/heroku/languages-github-actions.git"
rust-version = "1.74"
edition = "2021"
publish = false

[[bin]]
name = "actions"
path = "src/main.rs"

[profile.release]
strip = true

[lints.rust]
unreachable_pub = "warn"
unsafe_code = "warn"
unused_crate_dependencies = "warn"

[lints.clippy]
panic_in_result_fn = "warn"
pedantic = "warn"
unwrap_used = "warn"

[dependencies]
chrono = "0.4"
clap = { version = "4", default-features = false, features = [
    "derive",
    "error-context",
    "help",
    "std",
    "usage",
] }
ignore = "0.4"
indexmap = "2"
lazy_static = "1"
libcnb-common = "=0.16.0"
libcnb-data = "=0.16.0"
libcnb-package = "=0.16.0"
markdown = "1.0.0-alpha.15"
rand = "0.8"
regex = "1"
semver = "1"
serde_json = "1"
thiserror = "1"
toml_edit = "0.21"
uriparse = "0.6"

[dev-dependencies]
toml = "0.8"
