[package]
name = "languages-github-actions"
description = "GitHub Actions for the Languages Team"
version = "0.0.1"
repository = "https://github.com/heroku/languages-github-actions.git"
rust-version = "1.66"
edition = "2021"
publish = false

[[bin]]
name = "actions"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
clap = { version = "4", default-features = false, features = [
    "derive",
    "error-context",
    "help",
    "std",
    "usage",
] }
ignore = "0.4"
keep_a_changelog = { git = "https://github.com/colincasey/keep_a_changelog.git" }
libcnb-common = "=0.15.0"
libcnb-data = "=0.15.0"
libcnb-package = "=0.15.0"
rand = "0.8"
serde_json = "1"
thiserror = "1"
toml_edit = "0.19"
uriparse = "0.6"

[dev-dependencies]
toml = "0.7"
