[package]
name = "languages-github-actions"
description = "GitHub Actions for the Languages Team"
version = "0.3.1"
repository = "https://github.com/heroku/languages-github-actions.git"
rust-version = "1.66"
edition = "2021"
publish = false

[[bin]]
name = "actions"
path = "src/main.rs"

[profile.release]
strip = true

[dependencies]
chrono = "0.4"
clap = { version = "4", default-features = false, features = [
    "derive",
    "error-context",
    "help",
    "std",
    "usage",
] }
indexmap = "2"
lazy_static = "1"
libcnb-data = "=0.13.0"
libcnb-package = "=0.13.0"
markdown = "1.0.0-alpha.12"
rand = "0.8"
regex = "1"
semver = "1"
serde_json = "1"
toml_edit = "0.19"
uriparse = "0.6"

[dev-dependencies]
toml = "0.7"
