name: Save buildpack release artifacts
description: Saves various artifacts used in the buildpack release phases

inputs:
  buildpack_artifact_prefix:
    required: true
    description: The prefix name to use for any generated buildpack artifacts
  changes:
    required: true
    description: This content will be used in PRs and GitHub Releases created
  cnb_file:
    required: true
    description: The path to the package .cnb buildpack file
  docker_image:
    required: true
    description: The path to the compressed docker image

runs:
  using: composite
  steps:
    - name: Save Changelog
      shell: bash
      run: |
        cat << "EOF" > ./${{ inputs.buildpack_artifact_prefix }}.changes
        ${{ inputs.changes }}
        EOF
        cat ./${{ inputs.buildpack_artifact_prefix }}.changes

    - name: Ensure CNB file path
      shell: bash
      run: |
        if [ "${{ inputs.cnb_file }}" != "${{ inputs.buildpack_artifact_prefix }}.cnb" ]; then
          mv ${{ inputs.cnb_file }} ${{ inputs.buildpack_artifact_prefix }}.cnb
        fi

    - name: Ensure Docker image tarball path
      shell: bash
      if: ${{ inputs.docker_image }} != ${{ inputs.buildpack_artifact_prefix }}.tar.zst
      run: |
        if [ "${{ inputs.docker_image }}" != "${{ inputs.buildpack_artifact_prefix }}.tar.zst" ]; then
          mv ${{ inputs.docker_image }} ${{ inputs.buildpack_artifact_prefix }}.tar.zst
        fi

    - name: Cache artifacts
      uses: actions/cache/save@v3
      with:
        key: ${{ github.run_id }}-${{ inputs.buildpack_artifact_prefix }}
        path: |
          ${{ inputs.buildpack_artifact_prefix }}.cnb
          ${{ inputs.buildpack_artifact_prefix }}.tar.zst
          ${{ inputs.buildpack_artifact_prefix }}.changes
