name: Generate Buildpack Matrix
description: Generates a list of buildpack details for use in a matrix strategy `include` list

outputs:
  version:
    description: The version number that all buildpacks are set to
  buildpacks:
    description: The list of {buildpack_id, buildpack_version, buildpack_dir, buildpack_artifact_prefix, docker_repository} values for a buildpack formatted as a JSON array

runs:
  using: node16
  main: index.js
