name: Restore buildpack release artifacts
description: Restores various artifacts used in the buildpack release phases

inputs:
  buildpack_artifact_prefix:
    required: true
    description: The prefix name to use for any generated buildpack artifacts

outputs:
  changes_file:
    description: This content will be used in PRs and GitHub Releases created
    value: ${{ inputs.buildpack_artifact_prefix }}.changes
  cnb_file:
    description: The path to the package .cnb buildpack file
    value: ${{ inputs.buildpack_artifact_prefix }}.cnb
  docker_image:
    description: The path to the compressed docker image
    value: ${{ inputs.buildpack_artifact_prefix }}.tar.zst

runs:
  using: composite
  steps:
    - name: Restore cached assets
      uses: actions/cache/restore@v3
      with:
        fail-on-cache-miss: true
        key: ${{ github.run_id }}-${{ inputs.buildpack_artifact_prefix }}
        path: |
          ${{ inputs.buildpack_artifact_prefix }}.cnb
          ${{ inputs.buildpack_artifact_prefix }}.tar.zst
          ${{ inputs.buildpack_artifact_prefix }}.changes
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1
