name: Buildpack Artifact Prefix
description: Create an artifact prefix from a Buildpack ID that safe to use for paths

inputs:
  buildpack_id:
    required: true
    description: The buildpack id to cache artifacts for
outputs:
  prefix:
    description: A prefix that can be used safely when naming files
    value: ${{ steps.buildpack_artifact_prefix.outputs.value }}

runs:
  using: composite
  steps:
    - name: Generate buildpack artifact prefix from id
      id: buildpack_artifact_prefix
      shell: bash
      run: echo "value=$(sed -e "s/\//_/g" <<< "${{ inputs.buildpack_id }}")" >> $GITHUB_OUTPUT
