name: Detect

on:
  workflow_call:
    outputs:
      buildpacks:
        description: An array of (id, path) entries for each detected buildpack in JSON format
        value: ${{ jobs.release-detect.outputs.buildpacks }}

permissions:
  contents: read

jobs:
  release-detect:
    name: Detect
    runs-on: ubuntu-latest
    outputs:
      buildpacks: ${{ steps.generate-buildpack-matrix.outputs.buildpacks }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Buildpack Matrix
        id: generate-buildpack-matrix
        uses: heroku/languages-github-actions/.github/actions/generate-buildpack-matrix@main
