on:
  workflow_call:
    inputs:
      bump:
        description: Bump which coordinate? (major, minor, patch)
        required: true
        type: string
      app_id:
        description: Application ID of GitHub application (Linguist)
        type: string
        required: true
      declarations_starting_version:
        description: When generating markdown declarations for each release, what version should be the start?
        type: string
        required: false
    secrets:
      app_private_key:
        description: Private key of GitHub application (Linguist)
        required: true

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: pub-hk-ubuntu-22.04-small
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bump versions and update changelogs
        id: prepare
        uses: heroku/languages-github-actions/.github/actions/prepare-release@main
        with:
          bump: ${{ inputs.bump }}
          declarations_starting_version: ${{ inputs.declarations_starting_version }}

      - name: Generate changelog
        id: generate-changelog
        uses: heroku/languages-github-actions/.github/actions/generate-changelog@main
        with:
          version: ${{ steps.prepare.outputs.to_version }}

      - name: Get token for GH application (Linguist)
        uses: heroku/use-app-token-action@main
        id: generate-token
        with:
          app_id: ${{ inputs.app_id }}
          private_key: ${{ secrets.app_private_key }}

      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ steps.generate-token.outputs.app_token }}
          title: Prepare release v${{ steps.prepare.outputs.to_version }}
          commit-message: Prepare release v${{ steps.prepare.outputs.to_version }}
          branch: prepare/v${{ steps.prepare.outputs.to_version }}
          body: ${{ steps.generate-changelog.outputs.changelog }}
          labels: "automation"

      - name: Configure pull request
        if: steps.pr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.app_token }}
