name: Publish → CNB Registry

on:
  workflow_call:
    inputs:
      buildpack_id:
        required: true
        type: string
        description: The id of the buildpack to package
    # secrets:
    #   cnb_registry_token:
    #     description: The token to login to the CNB registry with

permissions:
  contents: read

jobs:
  release-publish-cnb-registry:
    name: Publish → CNB Registry
    runs-on: ubuntu-latest
    steps:
      - name: Restore buildpack release artifacts
        id: buildpack
        uses: heroku/languages-github-actions/.github/actions/restore-buildpack-release@main
        with:
          buildpack_id: ${{ inputs.buildpack_id }}
      - name: Install crane
        uses: buildpacks/github-actions/setup-tools@v5.2.0
      - name: Check if version is already in the registry
        id: check
        run: |
          export URL="https://registry.buildpacks.io/api/v1/buildpacks/${{ inputs.buildpack_id }}/${{ steps.buildpack.outputs.version }}"
          export EXISTS=$(if [ "$( curl -s -o /dev/null -I -w "%{http_code}" "${URL}")" = "200" ]; then echo 'true'; else echo 'false'; fi)
          echo "published_to_cnb_registry=${EXISTS}" >> $GITHUB_OUTPUT
#      - name: Calculate the buildpack image digest
#        id: digest
#        run: echo "value=$(crane digest ${{ steps.buildpack.outputs.docker_repository }}:${{ steps.buildpack.outputs.buildpack_version }})" >> "$GITHUB_OUTPUT"
#      - name: Register the new version with the CNB Buildpack Registry
#        if: steps.check.outputs.published_to_cnb_registry == 'false'
#        uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:5.0.1
#        with:
#          token: ${{ secrets.cnb_registry_token }}
#          id: ${{ inputs.buildpack_id }}
#          version: ${{ steps.buildpack.outputs.buildpack_version }}
#          address: ${{ steps.buildpack.outputs.docker_repository }}@${{ steps.digest.outputs.value }}
