name: _buildpacks-prepare-release

env:
  BOT_USER: heroku-linguist[bot]
  BOT_EMAIL: 136119646+heroku-linguist[bot]@users.noreply.github.com
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      bump:
        description: Bump which coordinate? (major, minor, patch)
        required: true
        type: string
      app_id:
        description: Application ID of GitHub application (Linguist)
        type: string
        required: true
      declarations_starting_version:
        description: When generating markdown declarations for each release, what version should be the start?
        type: string
        required: false
      ip_allowlisted_runner:
        description: The GitHub Actions runner to use to run jobs that require IP allow-list privileges
        type: string
        required: false
        default: pub-hk-ubuntu-22.04-small
    secrets:
      app_private_key:
        description: Private key of GitHub application (Linguist)
        required: true

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ${{ inputs.ip_allowlisted_runner }}
    steps:
      - name: Get token for GH application (Linguist)
        uses: heroku/use-app-token-action@main
        id: generate-token
        with:
          app_id: ${{ inputs.app_id }}
          private_key: ${{ secrets.app_private_key }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          # The token is used to set the local git config which is used to run authenticated git commands
          token: ${{ steps.generate-token.outputs.app_token }}

      # This will ensure commits made from this workflow are attributed to the bot user
      - name: Configure git
        run: |
          git config --global user.name ${{ env.BOT_USER }}
          git config --global user.email ${{ env.BOT_EMAIL }}

      - name: Install Languages CLI
        uses: heroku/languages-github-actions/.github/actions/install-languages-cli@main

      - name: Bump versions and update changelogs
        id: prepare
        run: |
          actions prepare-release \
            --bump ${{ inputs.bump }} \
            --repository-url https://github.com/${{ github.repository }} \
            ${{ inputs.declarations_starting_version && format('--declarations-starting-version {0}', inputs.declarations_starting_version) }}

      - name: Generate changelog
        id: generate-changelog
        run: actions generate-changelog --version ${{ steps.prepare.outputs.to_version }}

      - name: Create pull request
        id: pr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          token: ${{ steps.generate-token.outputs.app_token }}
          title: Prepare release v${{ steps.prepare.outputs.to_version }}
          commit-message: Prepare release v${{ steps.prepare.outputs.to_version }}
          branch: prepare/v${{ steps.prepare.outputs.to_version }}
          body: ${{ steps.generate-changelog.outputs.changelog }}
          labels: "automation"

      - name: Configure pull request
        if: steps.pr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.app_token }}
