name: _buildpacks-release-publish-github

on:
  workflow_call:
    inputs:
      buildpack_artifact_prefix:
        required: true
        type: string
        description: The prefix name to use for any generated buildpack artifacts
      buildpack_version:
        required: true
        type: string
        description: The version of the buildpack to package

permissions:
  contents: write

jobs:
  release-publish-github:
    name: Publish → GitHub
    runs-on: pub-hk-ubuntu-22.04-small
    steps:
      - name: Restore buildpack release artifacts
        id: artifacts
        uses: heroku/languages-github-actions/.github/actions/restore-buildpack-release@main
        with:
          buildpack_artifact_prefix: ${{ inputs.buildpack_artifact_prefix }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v${{ inputs.buildpack_version }}
          body_path: ${{ steps.artifacts.outputs.changes_file }}
          files: ${{ steps.artifacts.outputs.cnb_file }}
          fail_on_unmatched_files: true
