name: Update Builder

on:
  workflow_call:
    inputs:
      app_id:
        description: "GitHub application ID"
        type: string
        required: true
    secrets:
      app_private_key:
        description: "Private key of the GitHub application"
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  release-update-builder:
    name: Update Builder
    runs-on: pub-hk-ubuntu-22.04-small
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./buildpacks

      - name: Checkout builder repository
        uses: actions/checkout@v3
        with:
          repository: heroku/builder
          path: ./builder

      - name: Install crane
        uses: buildpacks/github-actions/setup-tools@v5.2.0

      - name: Update Builder
        uses: heroku/languages-github-actions/.github/actions/update-builder@main
        with:
          repository_path: ./buildpacks
          builder_repository_path: ./builder
          builders: |
            builder-22
            buildpacks-20

      - name: Get token from GitHub application (Linguist)
        uses: heroku/use-app-token-action@main
        id: generate-token
        with:
          app_id: ${{ inputs.app_id }}
          private_key: ${{ secrets.app_private_key }}

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.app_token }}
          title: Update ${{ github.repository }}
          path: ./builder
          branch: update/${{ github.repository }}
          body-path: ${{ steps.buildpack.outputs.changes_file }}

      - name: Configure PR
        if: steps.pr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash --repo heroku/builder "${{ steps.pr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.app_token }}
