name: Publish → GitHub

on:
  workflow_call:
    inputs:
      buildpack_id:
        required: true
        type: string
        description: The id of the buildpack to package

permissions:
  contents: write

jobs:
  release-publish-github:
    name: Publish → GitHub
    runs-on: pub-hk-ubuntu-22.04-small
    steps:
      - name: Restore buildpack release artifacts
        id: buildpack
        uses: heroku/languages-github-actions/.github/actions/restore-buildpack-release@main
        with:
          buildpack_id: ${{ inputs.buildpack_id }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.buildpack.outputs.buildpack_version }}
          body_path: ${{ steps.buildpack.outputs.changes_file }}
          files: ${{ steps.buildpack.outputs.cnb_file }}
          fail_on_unmatched_files: true
