name: Publish → Docker

on:
  workflow_call:
    inputs:
      buildpack_id:
        required: true
        type: string
        description: The id of the buildpack to package
    # secrets:
    #   docker_hub_user:
    #     description: The username to login to Docker Hub with
    #   docker_hub_token:
    #     description: The token to login to Docker Hub with

permissions:
  contents: read

jobs:
  release-publish-docker:
    name: Publish → Docker
    runs-on: ubuntu-latest
    steps:
      - name: Restore buildpack release artifacts
        id: buildpack
        uses: heroku/languages-github-actions/.github/actions/restore-buildpack-release@main
        with:
          buildpack_id: ${{ inputs.buildpack_id }}
      - name: Load Docker images into the Docker daemon
        run: zstd -dc --long=31 ${{ steps.buildpack.outputs.docker_image }} | docker load
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          registry: docker.io
#          username: ${{ secrets.docker_hub_user }}
#          password: ${{ secrets.docker_hub_token }}
      - name: Check if version is already on Docker Hub
        id: check
        run: echo "published_to_docker=$(docker manifest inspect "${{ steps.buildpack.outputs.docker_repository }}:${{ steps.buildpack.outputs.buildpack_version }}" &> /dev/null && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
      - name: Tag and publish buildpack
        if: steps.check.outputs.published_to_docker == 'false'
        run: |
          echo "TODO: Echoing these commands until we're sure these steps work"
          echo "docker tag ${{ inputs.buildpack_id }} ${{ steps.buildpack.outputs.docker_repository }}:${{ steps.buildpack.outputs.buildpack_version }}"
          echo "docker push ${{ steps.buildpack.outputs.docker_repository }}:${{ steps.buildpack.outputs.buildpack_version }}"
