on:
  workflow_call:
    inputs:
      buildpack_id:
        required: true
        type: string
        description: The id of the buildpack to package
      buildpack_version:
        required: true
        type: string
        description: The version of the buildpack to package
      docker_repository:
        required: true
        type: string
        description: The docker repository to publish the buildpack to
    secrets:
      cnb_registry_token:
        required: true
        description: The token to login to the CNB registry with

permissions:
  contents: read

jobs:
  release-publish-cnb-registry:
    name: Publish → CNB Registry
    runs-on: ubuntu-latest
    steps:
      - name: Install crane
        uses: buildpacks/github-actions/setup-tools@v5.3.0

      - name: Check if version is already in the registry
        id: check
        run: |
          export URL="https://registry.buildpacks.io/api/v1/buildpacks/${{ inputs.buildpack_id }}/${{ inputs.buildpack_version }}"
          export EXISTS=$(if [ "$( curl -s -o /dev/null -I -w "%{http_code}" "${URL}")" = "200" ]; then echo 'true'; else echo 'false'; fi)
          echo "published_to_cnb_registry=${EXISTS}" >> $GITHUB_OUTPUT

      - name: Calculate the buildpack image digest
        id: digest
        run: echo "value=$(crane digest ${{ inputs.docker_repository }}:${{ inputs.buildpack_version }})" >> "$GITHUB_OUTPUT"

      - name: Register the new version with the CNB Buildpack Registry
        if: steps.check.outputs.published_to_cnb_registry == 'false'
        uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:5.0.1
        with:
          token: ${{ secrets.cnb_registry_token }}
          id: ${{ inputs.buildpack_id }}
          version: ${{ inputs.buildpack_version }}
          address: ${{ inputs.docker_repository }}@${{ steps.digest.outputs.value }}
